name: Actions Workflow
on: 
  schedule:
    - cron: "0 12 * FEB 0"
  push:
  pull_request:
    types: [ opened, reopened, assigned ]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls 
          echo "${{ github.token }}" 
      # github.token - github token to authenticate the user

      - name: Simple JS Action
        id: greet # we have to ID if we want to use it in steps object
        uses: zivkovicmarko95/hello-world-javascript-action-@main
        with:
          who-to-greet: John

      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
