name: Actions Workflow
on: [ push ]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls 

      - name: Checkout 
        uses: actions/checkout # when something is done in this repository, then trigger this step

      - name: List Files After Checkout
        run: |
          pwd
          ls -a

      - name: Simple JS Action
        id: greet # we have to ID if we want to use it in steps object
        uses: zivkovicmarko95/hello-world-javascript-action-@main
        with:
          who-to-greet: John

      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
