name: Shell Commands
on: [ push ]
jobs:
  run-shell-command: # this is the name of the job
    runs-on: ubuntu-latest # it will be run on ubuntu
    steps: # steps that will be triggered
      - name: echo a string  # name of the step
        run: echo "Hello World" # command that needs to be run
      
      - name: multiline script
        run: | 
          node -v
          npm -v

      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python # shell that needs to be used if I want to run the commands

  run-windows-commands:
    runs-on: windows-latest
    needs: [ "run-shell-command" ] # array of the jobs that this job -> run-windows-commands depends on and it will run when the jobs finished in the needs array
    steps:
      - name: Directory PowerShell
        run: Get-Location

      - name: Directory Bash
        run: pwd
        shell: bash